services:
  final-projectt:
    image: final-projectt:latest
    build:
      context: .
    ports:
      - "8081:6060"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
       - "5434:5432"
